### ISSUE TITLE
[RULE] - Pick Flowers

### ISSUE THREAD

**Issue by DH12043** [Gilly7CE/Carpet-Addons-Not-Found#108]
### Proposed rule name 
pickFlowersFromPots

### Describe rule 
Right-clicking on a flowerpot with a flower in it will put the flower into your invantory

### Options for rule 
true / false

**Comment by Gilly7CE** [comment]
Similar to the eye of ender rule we have, so should be an easy implementation

**Comment by Gilly7CE** [comment]
There’s a consistency issue to consider too, maybe the rule name should be `dropFlowersFromPots` to be consistent with the eye of ender rule too? However, I do prefer the ‘pick..’ name…shame we didn’t use that for the eye of ender one

**Comment by Gilly7CE** [comment]
Decision is to use the `pick...` variant of the name. The consistency issue with `drop...` in the eye of ender rule is to be tackled later in the mod's lifetime.
