### ISSUE TITLE
[RULE] - PortalSpectatorDelay

### ISSUE THREAD

**Issue by Pi3tro88** [Gilly7CE/Carpet-Addons-Not-Found#113]
### Proposed rule name 
portalSpectatorDelay

### Describe rule 
like the rules for the other two gamemodes portalCreativeDelay and portalSurvivalDelay, it would be preatty useful to not enter the portal by accident with spectatorPlayersUsePortals

### Options for rule 
like the other rules, can be set by the player

**Comment by Gilly7CE** [comment]
Thanks for opening the issue! A good suggestion. This would be very useful and is something we overlooked...
