### ISSUE TITLE
[RULE] - replacable flower pots

### ISSUE THREAD

**Issue by Serzbiedry** [Gilly7CE/Carpet-Addons-Not-Found#118]
Rule name: replaceContentInFlowerPot

Desribtion: When right clicking a flower pot with a pottable item, it will replace the item that was in the pot with the new one.

Options: true/false or true,creativeOnly,false

**Comment by Gilly7CE** [comment]
Keep it simple with true/false. Categories could be `FEATURE`, `EXPERIMENTAL` and `CARPET-ADDONS-NOT-FOUND`

**Comment by Gilly7CE** [comment]
I accidentally linked the wrong issue to the mentioned PR...
