### ISSUE TITLE
[REQUEST] - 1.19.0 release

### ISSUE THREAD

**Issue by Serzbiedry** [Gilly7CE/Carpet-Addons-Not-Found#119]
1.19.0 is last version without chatReporting and many made desision to stay in this version, we should make sure 1.19.x version works for this version or make a branch specificly for 1.19.0.

**Comment by Gilly7CE** [comment]
If there was demand for it, sure. But we really should support the latest version in each one if we do. We only support 1.19.3 for my benefit as I use that in my YouTube series.
