### ISSUE TITLE
[BUG] - Client disconnect when entering a nether portal as a spectator in a multiplayer server.

### ISSUE THREAD

**Issue by Haaaaaaaa615** [Gilly7CE/Carpet-Addons-Not-Found#157]
### Description
 
When entering a nether portal in spectator with the rule spectatorPlayersUsePortals set to true, the client is disconnected with the error "Internal Exception: io.netty.handler.codec.EncoderException: java.io.IOException: Can't serialize unregistered packet"

### To Reproduce

1. Open multiplayer world
2. Do `/carpet spectatorPlayersUsePortals true`
3. Go into spectator mode
4. Enter portal
5. See error

### Expected behavior
The expected behavior was that the player would enter the nether portal and be transported to the nether.

### Screenshots
[latest.log](https://github.com/Gilly7CE/Carpet-Addons-Not-Found/files/11725315/latest.log)

### Version (please complete the following information):
 - Minecraft version: 1.19.4
 - Carpet version: 1.4.101+v230319
 - Mod version: 1.2.1

**Comment by Serzbiedry** [comment]
Can you provide what mods are you running on client along with its crash report?
