### ISSUE TITLE
[RELEASE] - Support 1.20.6 and 1.21

### ISSUE THREAD

**Issue by Gilly7CE** [Gilly7CE/Carpet-Addons-Not-Found#197]
Support is long overdue for 1.20.6 and now that 1.21 is out we need to support that too.

Order of tasks to do:

- [x] Update `1.20.x` branch to 1.20.6 release via a PR
- [x] Update `main` branch to 1.21.1 via a PR
- [x] Create release for 1.20.6
- [x] Create release for 1.21.1

**Comment by andopepe** [comment]
What's the eta on this? I've been waiting for this to update to go to 1.21 so just curious on if I should just disable it for now if itll be much longer

**Comment by Gilly7CE** [comment]
> What's the eta on this? I've been waiting for this to update to go to 1.21 so just curious on if I should just disable it for now if itll be much longer

@andopepe the 1.21.1 version of the mod has now released! 🙂 Apologies for the delay.

**Comment by andopepe** [comment]
Fantastic, appreciate the notice!
