### ISSUE TITLE
[ERROR] - <minecraft won't load>

### ISSUE THREAD

**Issue by TheFra1320** [Gilly7CE/Carpet-Addons-Not-Found#204]
### Description
 
when i try to open the version of minecraft with the mod on it won't open, and the only things that pop up is the fabric loader error 

### To Reproduce
just try to install carpet and carpet addon not found and it will crash

### Expected behavior
the game runs normally

### Screenshots
[crash_log_carpet_addon_not_found.txt](https://github.com/user-attachments/files/18165263/crash_log_carpet_addon_not_found.txt)
the log written on the fabric loader error

### Version (please complete the following information):
 - Minecraft version: 1.21
 - Carpet version: 1.21-1.4.147+v240613
 - Mod version: 1.20.6-1.3.1
 - fabric loader version: 0.16.9

### Additional context
i tryed to replicate the bug with the step in the "to reproduce" section but there the fabric loader error doesn't appear, if can help this is my mod list
[mod_list.txt](https://github.com/user-attachments/files/18165388/mod_list.txt)

**Comment by Gilly7CE** [comment]
Hi, thanks for your issue.

You need to use the 1.21 version of the mod not 1.20. Here is a link:
[1.21.1-v1.3.1](https://github.com/Gilly7CE/Carpet-Addons-Not-Found/releases/tag/1.21.1-v1.3.1)

**Comment by TheFra1320** [comment]
So why on modrinth the .20.6 is also for 1.21? And the .21.1 is just for the 1.21.1

**Comment by Gilly7CE** [comment]
> So why on modrinth the .20.6 is also for 1.21? And the .21.1 is just for the 1.21.1

Modrinth is wrong unfortunately but I’ll take a look into it when I have a chance

**Comment by TheFra1320** [comment]
Gilly7CE there's a problem:
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Carpet Addons Not Found' (carpet-addons-not-found) 1.3.1 with any version that is compatible with:
		 - minecraft 1.21
More details:
	 - Mod 'Carpet Addons Not Found' (carpet-addons-not-found) 1.3.1 requires version 1.21.1 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.21!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
 the error appear again but this time says that the mod is for 1.21.1 and not 1.21

**Comment by Gilly7CE** [comment]
You need Minecraft 1.21.1 not 1.21. We don’t support Minecraft 1.21
