### ISSUE TITLE
[RULE] - Disable mob spawning per dimension

### ISSUE THREAD

**Issue by Gilly7CE** [Gilly7CE/Carpet-Addons-Not-Found#91]
### Proposed rule name
Three rules:
- `disableMobSpawningInOverworld`
- `disableMobSpawningInNether`
- `disableMobSpawningInEnd`

### Describe rule
Mob spawning can be disabled in its entirety per dimension. Could be useful for creative testing of farms without disabling mob spawning as a whole with the gamerule. These should be given the `CREATIVE` category.

### Options for rule
`true` or `false` (default)

**Comment by Basicprogrammer10** [comment]
Would it be better to have just `mobSpawningInOverworld`, `mobSpawningInNether`, and `mobSpawningInEnd` with a default value of true?

**Comment by Gilly7CE** [comment]
> Would it be better to have just `mobSpawningInOverworld`, `mobSpawningInNether`, and `mobSpawningInEnd` with a default value of true?

The standard definitions for rules is that they modify the vanilla behaviour, so they’re always by default `false`. If we make the default behaviour `true` and use the rule names as you mention then that would break the pattern and it would read as carpet rules are enabled, which would technically be not not the case. “disable” is explicitly clear what we intend.

**Comment by Basicprogrammer10** [comment]
A few rules in [base carpet](https://github.com/gnembon/fabric-carpet/wiki/Current-Available-Settings) are true by default like `creativePlayersLoadChunks`, `fillUpdates`, `interactionUpdates`, and many more in rule expansion mods. So I don't think it would be that bad to have them true by default. I generally prefer the enable rules over disable ones, but a default value of false is ok.

As for the name, the default carpet rules that disable a vanilla feature when true seem to be in the format of `...Disabled` (`antiCheatDisabled`, `liquidDamageDisabled`). Should this format be used for these rules too?

**Comment by Gilly7CE** [comment]
> A few rules in [base carpet](https://github.com/gnembon/fabric-carpet/wiki/Current-Available-Settings) are true by default like `creativePlayersLoadChunks`, `fillUpdates`, `interactionUpdates`, and many more in rule expansion mods. So I don't think it would be that bad to have them true by default. I generally prefer the enable rules over disable ones, but a default value of false is ok.
> 
> As for the name, the default carpet rules that disable a vanilla feature when true seem to be in the format of `...Disabled` (`antiCheatDisabled`, `liquidDamageDisabled`). Should this format be used for these rules too?

Good points. However, we already have rules which start with `disable…` and consistency within the mod itself is also an important co sideration
