### ISSUE TITLE
[MC VERSION] - Support for 1.20

### ISSUE THREAD

**Issue by Gilly7CE** [Gilly7CE/Carpet-Addons-Not-Found#99]
We shall need to support 1.20 once it is released. Work on this should begin once carpet 1.20 has been released.

Additions to existing rules we will need:
- `netheriteAxeInstantMineWood`
  - Need to include the following blocks:
    - Bamboo Mosaic, and its variants (stairs, slabs etc.)
    - Bamboo Planks, and its variants (stairs, slabs etc.)
    - Block of Bamboo, and its stripped variant
    - Cherry Log, its stripped variant, and its wood variants
    - Cherry planks, and its variants (stairs, slabs etc.)

**Comment by Gilly7CE** [comment]
Also look at `spectatorPlayersUsePortals` as an offset is added which I suspect has been removed for 1.20 now.

**Comment by Serzbiedry** [comment]
Why no branch for this yet? :p

**Comment by Gilly7CE** [comment]
> Why no branch for this yet? :p

Because I’m waiting for the full carpet 1.20 (not pre release versions) plus it will be what `main` becomes. I’ll need to create a `1.19.4` from `main` 😛

**Comment by Gilly7CE** [comment]
1.20 update will release on **June 7th**, so need to create `1.20` branch then, or after.

**Comment by Gilly7CE** [comment]
`1.20.x` branch will be created from the `1.19.4` branch.

**Comment by Gilly7CE** [comment]
This branch will always be the latest version of 1.20. Once a patch version of 1.20 is released, support for the previous one is dropped.

**Comment by Gilly7CE** [comment]
Rules now broken:

- [ ] `alwaysPickFlowersFromPots` (the rule is now in 1.20 vanilla, so can be removed)
- [ ] `replaceableFlowers` (flowers won't drop as items)

**Comment by Gilly7CE** [comment]
`replaceableFlowers` was a false alarm since I simply cannot code

**Comment by Gilly7CE** [comment]
> Also look at `spectatorPlayersUsePortals` as an offset is added which I suspect has been removed for 1.20 now.

Offset still needed to go through a single nether portal block. I think the new change is to the camera position only, not the bounding box of the spectator player
